
citydat <- data.frame(
    cities = c("Amsterdam", "Antwerp", "Athens", "Austin", "Barcelona", "Beijing", "Belize", 
               "Bergamo", "Berlin", "Bologna", "Bordeaux",
               "Boston", "Bristol", "Brussels", "Buenos Aires", "Cape Town", "Chicago", "Columbus", 
               "Copenhagen", "Crete", "Denver", "Dublin", "Edinburgh", "Florence", "Geneva",
               "Ghent", "Girona", "Hawaii", "Hong Kong", "Istanbul", "Lisbon",
               "London", "Los Angeles", "Lyon", "Madrid", "Malaga", "Mallorca", "Manchester",
               "Melbourne", "Menorca", "Mexico City", "Milan", "Montreal", "Munich", "Naples",
               "Nashville", "New Orleans", "New York City", "Oakland", "Oslo", "Ottawa", "Paris",
               "Portland", "Porto", "Prague", "Quebec City", "Rio de Janeiro", "Rome", "San Diego",
               "San Francisco", "Santiago", "Seattle", "Sevilla", "Shanghai", "Singapore", "Stockholm",
               "Sydney", "Taipei", "Thessaloniki", "Tokyo", "Toronto", "Valencia", "Vancouver",
               "Vaud", "Venice", "Victoria", "Vienna", "Washington, D.C."),
    listings_url = c("http://data.insideairbnb.com/the-netherlands/north-holland/amsterdam/2020-08-18/data/listings.csv.gz", "http://data.insideairbnb.com/belgium/vlg/antwerp/2020-06-22/data/listings.csv.gz", "http://data.insideairbnb.com/greece/attica/athens/2020-06-16/data/listings.csv.gz", "http://data.insideairbnb.com/united-states/tx/austin/2020-08-30/data/listings.csv.gz", "http://data.insideairbnb.com/spain/catalonia/barcelona/2020-08-24/data/listings.csv.gz", "http://data.insideairbnb.com/china/beijing/beijing/2020-06-19/data/listings.csv.gz", "http://data.insideairbnb.com/belize/bz/belize/2020-06-25/data/listings.csv.gz",
                     "http://data.insideairbnb.com/italy/lombardia/bergamo/2020-06-29/data/listings.csv.gz", "http://data.insideairbnb.com/germany/be/berlin/2020-08-30/data/listings.csv.gz", "http://data.insideairbnb.com/italy/emilia-romagna/bologna/2020-08-31/data/listings.csv.gz", "http://data.insideairbnb.com/france/nouvelle-aquitaine/bordeaux/2020-08-29/data/listings.csv.gz",
                     "http://data.insideairbnb.com/united-states/ma/boston/2020-08-31/data/listings.csv.gz", "http://data.insideairbnb.com/united-kingdom/england/bristol/2020-06-18/data/listings.csv.gz", "http://data.insideairbnb.com/belgium/bru/brussels/2020-06-15/data/listings.csv.gz", "http://data.insideairbnb.com/argentina/ciudad-aut%C3%B3noma-de-buenos-aires/buenos-aires/2020-06-21/data/listings.csv.gz", "http://data.insideairbnb.com/south-africa/wc/cape-town/2020-06-21/data/listings.csv.gz", "http://data.insideairbnb.com/united-states/il/chicago/2020-08-30/data/listings.csv.gz", "http://data.insideairbnb.com/united-states/oh/columbus/2020-07-28/data/listings.csv.gz",
                     "http://data.insideairbnb.com/denmark/hovedstaden/copenhagen/2020-06-26/data/listings.csv.gz", "http://data.insideairbnb.com/greece/crete/crete/2020-06-23/data/listings.csv.gz", "http://data.insideairbnb.com/united-states/co/denver/2020-06-28/data/listings.csv.gz", "http://data.insideairbnb.com/ireland/leinster/dublin/2020-08-27/data/listings.csv.gz", "http://data.insideairbnb.com/united-kingdom/scotland/edinburgh/2020-08-28/data/listings.csv.gz", "http://data.insideairbnb.com/italy/toscana/florence/2020-08-31/data/listings.csv.gz", "http://data.insideairbnb.com/switzerland/geneva/geneva/2020-06-23/data/listings.csv.gz",
                     "http://data.insideairbnb.com/belgium/vlg/ghent/2020-06-18/data/listings.csv.gz", "http://data.insideairbnb.com/spain/catalonia/girona/2020-06-29/data/listings.csv.gz", "http://data.insideairbnb.com/united-states/hi/hawaii/2020-08-31/data/listings.csv.gz", "http://data.insideairbnb.com/china/hk/hong-kong/2020-06-15/data/listings.csv.gz", "http://data.insideairbnb.com/turkey/marmara/istanbul/2020-06-28/data/listings.csv.gz", "http://data.insideairbnb.com/portugal/lisbon/lisbon/2020-08-29/data/listings.csv.gz",
                     "http://data.insideairbnb.com/united-kingdom/england/london/2020-08-24/data/listings.csv.gz", "http://data.insideairbnb.com/united-states/ca/los-angeles/2020-08-20/data/listings.csv.gz", "http://data.insideairbnb.com/france/auvergne-rhone-alpes/lyon/2020-08-31/data/listings.csv.gz", "http://data.insideairbnb.com/spain/comunidad-de-madrid/madrid/2020-08-25/data/listings.csv.gz", "http://data.insideairbnb.com/spain/andaluc%C3%ADa/malaga/2020-06-30/data/listings.csv.gz", "http://data.insideairbnb.com/spain/islas-baleares/mallorca/2020-08-28/data/listings.csv.gz", "http://data.insideairbnb.com/united-kingdom/england/manchester/2016-04-10/data/listings.csv.gz",
                     "http://data.insideairbnb.com/australia/vic/melbourne/2020-08-20/data/listings.csv.gz", "http://data.insideairbnb.com/spain/islas-baleares/menorca/2020-06-30/data/listings.csv.gz", "http://data.insideairbnb.com/mexico/df/mexico-city/2020-06-20/data/listings.csv.gz", "http://data.insideairbnb.com/italy/lombardy/milan/2020-08-31/data/listings.csv.gz", "http://data.insideairbnb.com/canada/qc/montreal/2020-08-28/data/listings.csv.gz", "http://data.insideairbnb.com/germany/bv/munich/2020-06-20/data/listings.csv.gz", "http://data.insideairbnb.com/italy/campania/naples/2020-08-31/data/listings.csv.gz",
                     "http://data.insideairbnb.com/united-states/tn/nashville/2020-08-30/data/listings.csv.gz", "http://data.insideairbnb.com/united-states/la/new-orleans/2020-08-18/data/listings.csv.gz", "http://data.insideairbnb.com/united-states/ny/new-york-city/2020-08-15/data/listings.csv.gz", "http://data.insideairbnb.com/united-states/ca/oakland/2020-06-17/data/listings.csv.gz", "http://data.insideairbnb.com/norway/oslo/oslo/2020-07-27/data/listings.csv.gz", "http://data.insideairbnb.com/canada/on/ottawa/2020-08-25/data/listings.csv.gz", "http://data.insideairbnb.com/france/ile-de-france/paris/2020-08-22/data/listings.csv.gz",
                     "http://data.insideairbnb.com/united-states/or/portland/2020-07-07/data/listings.csv.gz", "http://data.insideairbnb.com/portugal/norte/porto/2020-08-27/data/listings.csv.gz", "http://data.insideairbnb.com/czech-republic/prague/prague/2020-06-28/data/listings.csv.gz", "http://data.insideairbnb.com/canada/qc/quebec-city/2020-08-23/data/listings.csv.gz", "http://data.insideairbnb.com/brazil/rj/rio-de-janeiro/2020-06-19/data/listings.csv.gz", "http://data.insideairbnb.com/italy/lazio/rome/2020-08-26/data/listings.csv.gz", "http://data.insideairbnb.com/united-states/ca/san-diego/2020-07-27/data/listings.csv.gz",
                     "http://data.insideairbnb.com/united-states/ca/san-francisco/2020-08-15/data/listings.csv.gz", "http://data.insideairbnb.com/chile/rm/santiago/2020-06-21/data/listings.csv.gz", "http://data.insideairbnb.com/united-states/wa/seattle/2020-06-17/data/listings.csv.gz", "http://data.insideairbnb.com/spain/andaluc%C3%ADa/sevilla/2020-06-29/data/listings.csv.gz", "http://data.insideairbnb.com/china/shanghai/shanghai/2020-06-20/data/listings.csv.gz", "http://data.insideairbnb.com/singapore/sg/singapore/2020-06-22/data/listings.csv.gz", "http://data.insideairbnb.com/sweden/stockholms-l%C3%A4n/stockholm/2020-06-26/data/listings.csv.gz",
                     "http://data.insideairbnb.com/australia/nsw/sydney/2020-08-20/data/listings.csv.gz", "http://data.insideairbnb.com/taiwan/northern-taiwan/taipei/2020-06-29/data/listings.csv.gz", "http://data.insideairbnb.com/greece/central-macedonia/thessaloniki/2020-06-16/data/listings.csv.gz", "http://data.insideairbnb.com/japan/kant%C5%8D/tokyo/2020-06-25/data/listings.csv.gz", "http://data.insideairbnb.com/canada/on/toronto/2020-08-18/data/listings.csv.gz", "http://data.insideairbnb.com/spain/vc/valencia/2020-08-30/data/listings.csv.gz", "http://data.insideairbnb.com/canada/bc/vancouver/2020-08-24/data/listings.csv.gz",
                     "http://data.insideairbnb.com/switzerland/vd/vaud/2020-08-17/data/listings.csv.gz", "http://data.insideairbnb.com/italy/veneto/venice/2020-08-21/data/listings.csv.gz", "http://data.insideairbnb.com/canada/bc/victoria/2020-06-25/data/listings.csv.gz", "http://data.insideairbnb.com/austria/vienna/vienna/2020-08-26/data/listings.csv.gz", "http://data.insideairbnb.com/united-states/dc/washington-dc/2020-08-30/data/listings.csv.gz"),
    neighbourhoods_url = c("http://data.insideairbnb.com/the-netherlands/north-holland/amsterdam/2020-08-18/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/belgium/vlg/antwerp/2020-06-22/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/greece/attica/athens/2020-06-16/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/united-states/tx/austin/2020-08-30/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/spain/catalonia/barcelona/2020-08-24/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/china/beijing/beijing/2020-06-19/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/belize/bz/belize/2020-06-25/visualisations/neighbourhoods.geojson",
                           "http://data.insideairbnb.com/italy/lombardia/bergamo/2020-06-29/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/germany/be/berlin/2020-08-30/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/italy/emilia-romagna/bologna/2020-08-31/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/france/nouvelle-aquitaine/bordeaux/2020-08-29/visualisations/neighbourhoods.geojson",
                           "http://data.insideairbnb.com/united-states/ma/boston/2020-08-31/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/united-kingdom/england/bristol/2020-06-18/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/belgium/bru/brussels/2020-06-15/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/argentina/ciudad-aut%C3%B3noma-de-buenos-aires/buenos-aires/2020-06-21/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/south-africa/wc/cape-town/2020-06-21/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/united-states/il/chicago/2020-08-30/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/united-states/oh/columbus/2020-07-28/visualisations/neighbourhoods.geojson",
                           "http://data.insideairbnb.com/denmark/hovedstaden/copenhagen/2020-06-26/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/greece/crete/crete/2020-06-23/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/united-states/co/denver/2020-06-28/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/ireland/leinster/dublin/2020-08-27/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/united-kingdom/scotland/edinburgh/2020-08-28/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/italy/toscana/florence/2020-08-31/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/switzerland/geneva/geneva/2020-06-23/visualisations/neighbourhoods.geojson",
                           "http://data.insideairbnb.com/belgium/vlg/ghent/2020-06-18/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/spain/catalonia/girona/2020-06-29/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/united-states/hi/hawaii/2020-08-31/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/china/hk/hong-kong/2020-06-15/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/turkey/marmara/istanbul/2020-06-28/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/portugal/lisbon/lisbon/2020-08-29/visualisations/neighbourhoods.geojson",
                           "http://data.insideairbnb.com/united-kingdom/england/london/2020-08-24/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/united-states/ca/los-angeles/2020-08-20/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/france/auvergne-rhone-alpes/lyon/2020-08-31/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/spain/comunidad-de-madrid/madrid/2020-08-25/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/spain/andaluc%C3%ADa/malaga/2020-06-30/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/spain/islas-baleares/mallorca/2020-08-28/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/united-kingdom/england/manchester/2016-04-10/visualisations/neighbourhoods.geojson",
                           "http://data.insideairbnb.com/australia/vic/melbourne/2020-08-20/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/spain/islas-baleares/menorca/2020-06-30/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/mexico/df/mexico-city/2020-06-20/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/italy/lombardy/milan/2020-08-31/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/canada/qc/montreal/2020-08-28/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/germany/bv/munich/2020-06-20/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/italy/campania/naples/2020-08-31/visualisations/neighbourhoods.geojson",
                           "http://data.insideairbnb.com/united-states/tn/nashville/2020-08-30/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/united-states/la/new-orleans/2020-08-18/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/united-states/ny/new-york-city/2020-08-15/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/united-states/ca/oakland/2020-06-17/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/norway/oslo/oslo/2020-07-27/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/canada/on/ottawa/2020-08-25/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/france/ile-de-france/paris/2020-08-22/visualisations/neighbourhoods.geojson",
                           "http://data.insideairbnb.com/united-states/or/portland/2020-07-07/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/portugal/norte/porto/2020-08-27/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/czech-republic/prague/prague/2020-06-28/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/canada/qc/quebec-city/2020-08-23/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/brazil/rj/rio-de-janeiro/2020-06-19/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/italy/lazio/rome/2020-08-26/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/united-states/ca/san-diego/2020-07-27/visualisations/neighbourhoods.geojson",
                           "http://data.insideairbnb.com/united-states/ca/san-francisco/2020-08-15/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/chile/rm/santiago/2020-06-21/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/united-states/wa/seattle/2020-06-17/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/spain/andaluc%C3%ADa/sevilla/2020-06-29/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/china/shanghai/shanghai/2020-06-20/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/singapore/sg/singapore/2020-06-22/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/sweden/stockholms-l%C3%A4n/stockholm/2020-06-26/visualisations/neighbourhoods.geojson",
                           "http://data.insideairbnb.com/australia/nsw/sydney/2020-08-20/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/taiwan/northern-taiwan/taipei/2020-06-29/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/greece/central-macedonia/thessaloniki/2020-06-16/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/japan/kant%C5%8D/tokyo/2020-06-25/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/canada/on/toronto/2020-08-18/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/spain/vc/valencia/2020-08-30/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/canada/bc/vancouver/2020-08-24/visualisations/neighbourhoods.geojson",
                           "http://data.insideairbnb.com/switzerland/vd/vaud/2020-08-17/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/italy/veneto/venice/2020-08-21/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/canada/bc/victoria/2020-06-25/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/austria/vienna/vienna/2020-08-26/visualisations/neighbourhoods.geojson", "http://data.insideairbnb.com/united-states/dc/washington-dc/2020-08-30/visualisations/neighbourhoods.geojson")
)

# Objects for graphs

choices_graph <- c("Daily price (price)",
                   "Logarithm of daily price (log_price)",
                   "Neighbourhood (neighbourhood_cleansed)",
                   "Maximum number of guests (accommodates)",
                   "Latitude (latitude)",
                   "Longitude (longitude)",
                   "Property type (property_type)",
                   "Room type (room_type)",
                   "Number of bedrooms (bedrooms)",
                   "Number of bathrooms (bathrooms)",
                   "Number of beds (beds)",
                   "Annual availability (availability_365)",
                   "Number of reviews (number_of_reviews)",
                   "Average rating from reviews (review_scores_rating)",
                   "Instant booking possible? (instant_bookable)",
                   "Is host a superhost? (host_is_superhost)",
                   "Number of AirBNB listings by the host (host_listings_count)",
                   "Host acceptance rate (host_acceptance_rate)")

# numeric_var <- sapply(1:ncol(listings), function(i) ifelse(class(listings[,i]) == "numeric", colnames(listings)[i], ""))
# logical_var <- sapply(1:ncol(listings), function(i) ifelse(class(listings[,i]) == "logical", colnames(listings)[i], ""))
# integer_var <- sapply(1:ncol(listings), function(i) ifelse(class(listings[,i]) == "integer", colnames(listings)[i], ""))
# character_var <- sapply(1:ncol(listings), function(i) ifelse(class(listings[,i]) == "character", colnames(listings)[i], ""))

